const MessageType = {
    PROPAGATE_NAME: 'PROPAGATE_NAME',
    UPDATE_PLAYER_DATA: 'UPDATE_PLAYER_DATA',
    GET_READY: 'GET_READY',
    SEEK_FOR_OPONENT: 'SEEK_FOR_OPONENT',
    MOVE: 'MOVE',
    DISCONNECT: 'DISCONNECT'
}